name: BYTEFLOW Docker Compose Setup

services:
  app:
    build:
      context: .
      args:
        CONTENTFUL_SPACE_ID: ${CONTENTFUL_SPACE_ID}
        CONTENTFUL_ACCESS_TOKEN: ${CONTENTFUL_ACCESS_TOKEN}
        CONTENTFUL_PERSONAL_ACCESS_TOKEN: ${CONTENTFUL_PERSONAL_ACCESS_TOKEN}
    restart: unless-stopped
    expose:
      - "3000"
    env_file: .env

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

  db:
    image: postgres:18-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "100.103.113.18:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  caddy_data:
  db_data:
  